-- GENERATED by scripts/db-schema.sh - do not edit.
-- Rebuild: ./scripts/db-schema.sh

--
-- PostgreSQL database dump
--

\restrict 2lAiTYoblmNOhdg2xD0wEgTo6yK2VtMijlt2TPyAGdBEZG6BaYAYxEQrNq4qWxL

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: ledger; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA ledger;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: entry; Type: TABLE; Schema: ledger; Owner: -
--

CREATE TABLE ledger.entry (
    id bigint NOT NULL,
    transaction_id text NOT NULL,
    request_id text NOT NULL,
    kind text NOT NULL,
    account text NOT NULL,
    amount bigint NOT NULL,
    currency text NOT NULL,
    jurisdiction text,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: entry_id_seq; Type: SEQUENCE; Schema: ledger; Owner: -
--

ALTER TABLE ledger.entry ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME ledger.entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: merchant_balance; Type: VIEW; Schema: ledger; Owner: -
--

CREATE VIEW ledger.merchant_balance AS
 SELECT split_part(account, ':'::text, 2) AS merchant_id,
    currency,
    (- sum(amount)) AS owed
   FROM ledger.entry
  WHERE (account ~~ 'merchant:%'::text)
  GROUP BY (split_part(account, ':'::text, 2)), currency;


--
-- Name: tax_liability; Type: VIEW; Schema: ledger; Owner: -
--

CREATE VIEW ledger.tax_liability AS
 SELECT jurisdiction,
    currency,
    (- sum(amount)) AS owed
   FROM ledger.entry
  WHERE (account ~~ 'tax:%'::text)
  GROUP BY jurisdiction, currency;


--
-- Name: entry entry_pkey; Type: CONSTRAINT; Schema: ledger; Owner: -
--

ALTER TABLE ONLY ledger.entry
    ADD CONSTRAINT entry_pkey PRIMARY KEY (id);


--
-- Name: entry_account_idx; Type: INDEX; Schema: ledger; Owner: -
--

CREATE INDEX entry_account_idx ON ledger.entry USING btree (account, currency);


--
-- Name: entry_idempotency_idx; Type: INDEX; Schema: ledger; Owner: -
--

CREATE UNIQUE INDEX entry_idempotency_idx ON ledger.entry USING btree (request_id, account);


--
-- Name: entry_jurisdiction_idx; Type: INDEX; Schema: ledger; Owner: -
--

CREATE INDEX entry_jurisdiction_idx ON ledger.entry USING btree (jurisdiction, currency, occurred_at) WHERE (jurisdiction IS NOT NULL);


--
-- Name: entry_transaction_idx; Type: INDEX; Schema: ledger; Owner: -
--

CREATE INDEX entry_transaction_idx ON ledger.entry USING btree (transaction_id);


--
-- PostgreSQL database dump complete
--

\unrestrict 2lAiTYoblmNOhdg2xD0wEgTo6yK2VtMijlt2TPyAGdBEZG6BaYAYxEQrNq4qWxL

