-- GENERATED by scripts/db-schema.sh - do not edit.
-- Rebuild: ./scripts/db-schema.sh

--
-- PostgreSQL database dump
--

\restrict aOH5YJMnidzmhbeYzsk5UqfUbKxPhPahFcCVSyeVRBcKDYw6THKTOtyn8QxgbGH

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: jobs; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA jobs;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: task; Type: TABLE; Schema: jobs; Owner: -
--

CREATE TABLE jobs.task (
    request_id text NOT NULL,
    machine_id smallint NOT NULL,
    state smallint NOT NULL,
    context jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    step smallint DEFAULT 1 NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    next_run_at timestamp with time zone DEFAULT now() NOT NULL,
    locked_until timestamp with time zone,
    locked_by text
);


--
-- Name: task_state; Type: TABLE; Schema: jobs; Owner: -
--

CREATE TABLE jobs.task_state (
    request_id text NOT NULL,
    state smallint NOT NULL,
    error_message text,
    attempts integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: task task_pkey; Type: CONSTRAINT; Schema: jobs; Owner: -
--

ALTER TABLE ONLY jobs.task
    ADD CONSTRAINT task_pkey PRIMARY KEY (request_id);


--
-- Name: task_due_idx; Type: INDEX; Schema: jobs; Owner: -
--

CREATE INDEX task_due_idx ON jobs.task USING btree (next_run_at) WHERE (state = 1);


--
-- Name: task_idempotency_key; Type: INDEX; Schema: jobs; Owner: -
--

CREATE UNIQUE INDEX task_idempotency_key ON jobs.task USING btree (machine_id, request_id) WHERE (state = 1);


--
-- Name: task_state_idx; Type: INDEX; Schema: jobs; Owner: -
--

CREATE UNIQUE INDEX task_state_idx ON jobs.task_state USING btree (request_id, state);


--
-- Name: task_state task_state_request_id_fkey; Type: FK CONSTRAINT; Schema: jobs; Owner: -
--

ALTER TABLE ONLY jobs.task_state
    ADD CONSTRAINT task_state_request_id_fkey FOREIGN KEY (request_id) REFERENCES jobs.task(request_id);


--
-- PostgreSQL database dump complete
--

\unrestrict aOH5YJMnidzmhbeYzsk5UqfUbKxPhPahFcCVSyeVRBcKDYw6THKTOtyn8QxgbGH

