-- GENERATED by scripts/db-schema.sh - do not edit.
-- Rebuild: ./scripts/db-schema.sh

--
-- PostgreSQL database dump
--

\restrict Bql0HVZpzafUEA9AsdsOqn0ZjVvrFzub1f48qQS6tvRCL30cMC7UGDc2oSfLDGa

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: mor; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA mor;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ledger_entry; Type: TABLE; Schema: mor; Owner: -
--

CREATE TABLE mor.ledger_entry (
    id bigint NOT NULL,
    transaction_id uuid NOT NULL,
    purpose smallint NOT NULL,
    purpose_key text,
    amount numeric(19,4) NOT NULL,
    currency text NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    settled_by_transaction_id uuid,
    CONSTRAINT ledger_entry_amount_ck CHECK ((amount <> (0)::numeric)),
    CONSTRAINT ledger_entry_currency_ck CHECK ((currency ~ '^[A-Z]{3}$'::text)),
    CONSTRAINT ledger_entry_purpose_ck CHECK ((purpose = ANY (ARRAY[1, 2, 3, 4, 5, 6])))
);


--
-- Name: ledger_entry_id_seq; Type: SEQUENCE; Schema: mor; Owner: -
--

ALTER TABLE mor.ledger_entry ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME mor.ledger_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ledger_transaction; Type: TABLE; Schema: mor; Owner: -
--

CREATE TABLE mor.ledger_transaction (
    id uuid NOT NULL,
    type smallint NOT NULL,
    payment_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ledger_transaction_type_ck CHECK ((type = ANY (ARRAY[1, 2, 3, 4])))
);


--
-- Name: merchant; Type: TABLE; Schema: mor; Owner: -
--

CREATE TABLE mor.merchant (
    id uuid NOT NULL,
    name text NOT NULL,
    currency text NOT NULL,
    fee_rate_bps integer NOT NULL,
    tax_category smallint NOT NULL,
    status smallint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT merchant_currency_ck CHECK ((currency ~ '^[A-Z]{3}$'::text)),
    CONSTRAINT merchant_fee_rate_ck CHECK (((fee_rate_bps >= 0) AND (fee_rate_bps <= 10000))),
    CONSTRAINT merchant_status_ck CHECK ((status = ANY (ARRAY[1, 2]))),
    CONSTRAINT merchant_tax_category_ck CHECK ((tax_category = ANY (ARRAY[1, 2])))
);


--
-- Name: merchant_daily_balance; Type: TABLE; Schema: mor; Owner: -
--

CREATE TABLE mor.merchant_daily_balance (
    merchant_id uuid NOT NULL,
    balance_date date NOT NULL,
    balance numeric(19,4) NOT NULL,
    currency text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT mdb_currency_ck CHECK ((currency ~ '^[A-Z]{3}$'::text))
);


--
-- Name: merchant_payment_details; Type: TABLE; Schema: mor; Owner: -
--

CREATE TABLE mor.merchant_payment_details (
    merchant_id uuid NOT NULL,
    psp_account_id text NOT NULL,
    account_holder text NOT NULL,
    iban text,
    bic text,
    account_number text,
    routing_code text,
    bank_country text NOT NULL,
    address jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT mpd_bank_country_ck CHECK ((bank_country ~ '^[A-Z]{2}$'::text)),
    CONSTRAINT mpd_identifiers_ck CHECK (((iban IS NOT NULL) OR ((account_number IS NOT NULL) AND (routing_code IS NOT NULL))))
);


--
-- Name: payment; Type: TABLE; Schema: mor; Owner: -
--

CREATE TABLE mor.payment (
    id uuid NOT NULL,
    psp_reference text NOT NULL,
    merchant_id uuid,
    gross numeric(19,4) NOT NULL,
    tax numeric(19,4) NOT NULL,
    fee numeric(19,4) NOT NULL,
    merchant_net numeric(19,4) NOT NULL,
    currency text NOT NULL,
    tax_country text,
    tax_category smallint,
    tax_rate_bps integer,
    reverse_charge boolean DEFAULT false NOT NULL,
    evidence jsonb NOT NULL,
    status smallint NOT NULL,
    payment_time timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT payment_amounts_ck CHECK (((gross > (0)::numeric) AND (tax >= (0)::numeric) AND (fee >= (0)::numeric) AND (merchant_net >= (0)::numeric))),
    CONSTRAINT payment_country_ck CHECK (((tax_country IS NULL) OR (tax_country ~ '^[A-Z]{2}$'::text))),
    CONSTRAINT payment_currency_ck CHECK ((currency ~ '^[A-Z]{3}$'::text)),
    CONSTRAINT payment_split_ck CHECK ((gross = ((tax + fee) + merchant_net))),
    CONSTRAINT payment_status_ck CHECK ((status = ANY (ARRAY[1, 4, 5])))
);


--
-- Name: payment_hold; Type: TABLE; Schema: mor; Owner: -
--

CREATE TABLE mor.payment_hold (
    payment_id uuid NOT NULL,
    reason smallint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    resolved_at timestamp with time zone,
    CONSTRAINT payment_hold_reason_ck CHECK ((reason = ANY (ARRAY[1, 2])))
);


--
-- Name: payout; Type: TABLE; Schema: mor; Owner: -
--

CREATE TABLE mor.payout (
    merchant_id uuid NOT NULL,
    payout_date date NOT NULL,
    amount numeric(19,4) NOT NULL,
    currency text NOT NULL,
    ledger_transaction_id uuid NOT NULL,
    status smallint NOT NULL,
    psp_reference text,
    claimed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT payout_amount_ck CHECK ((amount > (0)::numeric)),
    CONSTRAINT payout_currency_ck CHECK ((currency ~ '^[A-Z]{3}$'::text)),
    CONSTRAINT payout_status_ck CHECK ((status = ANY (ARRAY[1, 2, 3, 4])))
);


--
-- Name: processing_error; Type: TABLE; Schema: mor; Owner: -
--

CREATE TABLE mor.processing_error (
    id uuid NOT NULL,
    event_type smallint NOT NULL,
    external_reference text NOT NULL,
    payload jsonb NOT NULL,
    error_code smallint NOT NULL,
    error_detail text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT processing_error_code_ck CHECK ((error_code = ANY (ARRAY[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]))),
    CONSTRAINT processing_error_event_ck CHECK ((event_type = ANY (ARRAY[1, 2, 3, 4])))
);


--
-- Name: refund; Type: TABLE; Schema: mor; Owner: -
--

CREATE TABLE mor.refund (
    id uuid NOT NULL,
    refund_reference text NOT NULL,
    payment_id uuid NOT NULL,
    ledger_transaction_id uuid NOT NULL,
    amount numeric(19,4) NOT NULL,
    currency text NOT NULL,
    reason smallint NOT NULL,
    fee_returned boolean NOT NULL,
    refunded_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT refund_amount_ck CHECK ((amount > (0)::numeric)),
    CONSTRAINT refund_currency_ck CHECK ((currency ~ '^[A-Z]{3}$'::text)),
    CONSTRAINT refund_reason_ck CHECK ((reason = ANY (ARRAY[1, 2, 3, 4, 5])))
);


--
-- Name: tax_daily_balance; Type: TABLE; Schema: mor; Owner: -
--

CREATE TABLE mor.tax_daily_balance (
    country text NOT NULL,
    balance_date date NOT NULL,
    balance numeric(19,4) NOT NULL,
    currency text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT tdb_country_ck CHECK ((country ~ '^[A-Z]{2}$'::text)),
    CONSTRAINT tdb_currency_ck CHECK ((currency ~ '^[A-Z]{3}$'::text))
);


--
-- Name: tax_rate; Type: TABLE; Schema: mor; Owner: -
--

CREATE TABLE mor.tax_rate (
    country text NOT NULL,
    category smallint NOT NULL,
    valid_from date NOT NULL,
    rate_bps integer NOT NULL,
    CONSTRAINT tax_rate_bps_ck CHECK (((rate_bps >= 0) AND (rate_bps <= 10000))),
    CONSTRAINT tax_rate_category_ck CHECK ((category = ANY (ARRAY[1, 2]))),
    CONSTRAINT tax_rate_country_ck CHECK ((country ~ '^[A-Z]{2}$'::text))
);


--
-- Name: tax_remittance; Type: TABLE; Schema: mor; Owner: -
--

CREATE TABLE mor.tax_remittance (
    country text NOT NULL,
    period_start date NOT NULL,
    amount numeric(19,4) NOT NULL,
    currency text NOT NULL,
    ledger_transaction_id uuid NOT NULL,
    status smallint NOT NULL,
    reference text,
    claimed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT tax_remittance_amount_ck CHECK ((amount > (0)::numeric)),
    CONSTRAINT tax_remittance_country_ck CHECK ((country ~ '^[A-Z]{2}$'::text)),
    CONSTRAINT tax_remittance_currency_ck CHECK ((currency ~ '^[A-Z]{3}$'::text)),
    CONSTRAINT tax_remittance_status_ck CHECK ((status = ANY (ARRAY[1, 2, 3, 4])))
);


--
-- Name: ledger_entry ledger_entry_pkey; Type: CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.ledger_entry
    ADD CONSTRAINT ledger_entry_pkey PRIMARY KEY (id);


--
-- Name: ledger_transaction ledger_transaction_pkey; Type: CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.ledger_transaction
    ADD CONSTRAINT ledger_transaction_pkey PRIMARY KEY (id);


--
-- Name: merchant_daily_balance merchant_daily_balance_pkey; Type: CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.merchant_daily_balance
    ADD CONSTRAINT merchant_daily_balance_pkey PRIMARY KEY (merchant_id, balance_date);


--
-- Name: merchant_payment_details merchant_payment_details_pkey; Type: CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.merchant_payment_details
    ADD CONSTRAINT merchant_payment_details_pkey PRIMARY KEY (merchant_id);


--
-- Name: merchant merchant_pkey; Type: CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.merchant
    ADD CONSTRAINT merchant_pkey PRIMARY KEY (id);


--
-- Name: payment_hold payment_hold_pkey; Type: CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.payment_hold
    ADD CONSTRAINT payment_hold_pkey PRIMARY KEY (payment_id, reason);


--
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id);


--
-- Name: payout payout_pkey; Type: CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.payout
    ADD CONSTRAINT payout_pkey PRIMARY KEY (merchant_id, payout_date);


--
-- Name: processing_error processing_error_pkey; Type: CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.processing_error
    ADD CONSTRAINT processing_error_pkey PRIMARY KEY (id);


--
-- Name: refund refund_pkey; Type: CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.refund
    ADD CONSTRAINT refund_pkey PRIMARY KEY (id);


--
-- Name: tax_daily_balance tax_daily_balance_pkey; Type: CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.tax_daily_balance
    ADD CONSTRAINT tax_daily_balance_pkey PRIMARY KEY (country, balance_date);


--
-- Name: tax_rate tax_rate_pkey; Type: CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.tax_rate
    ADD CONSTRAINT tax_rate_pkey PRIMARY KEY (country, category, valid_from);


--
-- Name: tax_remittance tax_remittance_pkey; Type: CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.tax_remittance
    ADD CONSTRAINT tax_remittance_pkey PRIMARY KEY (country, period_start);


--
-- Name: ledger_entry_balance_idx; Type: INDEX; Schema: mor; Owner: -
--

CREATE INDEX ledger_entry_balance_idx ON mor.ledger_entry USING btree (purpose, purpose_key, currency, occurred_at);


--
-- Name: ledger_entry_transaction_idx; Type: INDEX; Schema: mor; Owner: -
--

CREATE INDEX ledger_entry_transaction_idx ON mor.ledger_entry USING btree (transaction_id);


--
-- Name: ledger_entry_settlement_transaction_idx; Type: INDEX; Schema: mor; Owner: -
--

CREATE INDEX ledger_entry_settlement_transaction_idx ON mor.ledger_entry USING btree (settled_by_transaction_id) WHERE (settled_by_transaction_id IS NOT NULL);


--
-- Name: ledger_entry_unsettled_merchant_idx; Type: INDEX; Schema: mor; Owner: -
--

CREATE INDEX ledger_entry_unsettled_merchant_idx ON mor.ledger_entry USING btree (purpose, purpose_key, currency, id) WHERE (settled_by_transaction_id IS NULL);


--
-- Name: ledger_transaction_payment_idx; Type: INDEX; Schema: mor; Owner: -
--

CREATE INDEX ledger_transaction_payment_idx ON mor.ledger_transaction USING btree (payment_id);


--
-- Name: merchant_daily_balance_idx; Type: INDEX; Schema: mor; Owner: -
--

CREATE INDEX merchant_daily_balance_idx ON mor.merchant_daily_balance USING btree (merchant_id, balance_date DESC);


--
-- Name: payment_hold_active_idx; Type: INDEX; Schema: mor; Owner: -
--

CREATE INDEX payment_hold_active_idx ON mor.payment_hold USING btree (payment_id) WHERE (resolved_at IS NULL);


--
-- Name: payment_merchant_idx; Type: INDEX; Schema: mor; Owner: -
--

CREATE INDEX payment_merchant_idx ON mor.payment USING btree (merchant_id, payment_time);


--
-- Name: payment_psp_reference_uk; Type: INDEX; Schema: mor; Owner: -
--

CREATE UNIQUE INDEX payment_psp_reference_uk ON mor.payment USING btree (psp_reference);


--
-- Name: payout_date_idx; Type: INDEX; Schema: mor; Owner: -
--

CREATE INDEX payout_date_idx ON mor.payout USING btree (payout_date);


--
-- Name: payout_due_idx; Type: INDEX; Schema: mor; Owner: -
--

CREATE INDEX payout_due_idx ON mor.payout USING btree (status, claimed_at, payout_date, merchant_id);


--
-- Name: payout_ledger_transaction_uk; Type: INDEX; Schema: mor; Owner: -
--

CREATE UNIQUE INDEX payout_ledger_transaction_uk ON mor.payout USING btree (ledger_transaction_id);


--
-- Name: processing_error_created_idx; Type: INDEX; Schema: mor; Owner: -
--

CREATE INDEX processing_error_created_idx ON mor.processing_error USING btree (created_at);


--
-- Name: processing_error_uk; Type: INDEX; Schema: mor; Owner: -
--

CREATE UNIQUE INDEX processing_error_uk ON mor.processing_error USING btree (event_type, external_reference, error_code);


--
-- Name: refund_ledger_transaction_uk; Type: INDEX; Schema: mor; Owner: -
--

CREATE UNIQUE INDEX refund_ledger_transaction_uk ON mor.refund USING btree (ledger_transaction_id);


--
-- Name: refund_payment_idx; Type: INDEX; Schema: mor; Owner: -
--

CREATE INDEX refund_payment_idx ON mor.refund USING btree (payment_id);


--
-- Name: refund_reference_uk; Type: INDEX; Schema: mor; Owner: -
--

CREATE UNIQUE INDEX refund_reference_uk ON mor.refund USING btree (refund_reference);


--
-- Name: tax_daily_balance_idx; Type: INDEX; Schema: mor; Owner: -
--

CREATE INDEX tax_daily_balance_idx ON mor.tax_daily_balance USING btree (country, balance_date DESC);


--
-- Name: tax_remittance_due_idx; Type: INDEX; Schema: mor; Owner: -
--

CREATE INDEX tax_remittance_due_idx ON mor.tax_remittance USING btree (status, claimed_at, period_start, country);


--
-- Name: tax_remittance_ledger_transaction_uk; Type: INDEX; Schema: mor; Owner: -
--

CREATE UNIQUE INDEX tax_remittance_ledger_transaction_uk ON mor.tax_remittance USING btree (ledger_transaction_id);


--
-- Name: ledger_entry ledger_entry_settled_by_transaction_id_fkey; Type: FK CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.ledger_entry
    ADD CONSTRAINT ledger_entry_settled_by_transaction_id_fkey FOREIGN KEY (settled_by_transaction_id) REFERENCES mor.ledger_transaction(id);


--
-- Name: ledger_entry ledger_entry_transaction_id_fkey; Type: FK CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.ledger_entry
    ADD CONSTRAINT ledger_entry_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES mor.ledger_transaction(id);


--
-- Name: ledger_transaction ledger_transaction_payment_id_fkey; Type: FK CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.ledger_transaction
    ADD CONSTRAINT ledger_transaction_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES mor.payment(id);


--
-- Name: merchant_daily_balance merchant_daily_balance_merchant_id_fkey; Type: FK CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.merchant_daily_balance
    ADD CONSTRAINT merchant_daily_balance_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES mor.merchant(id);


--
-- Name: merchant_payment_details merchant_payment_details_merchant_id_fkey; Type: FK CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.merchant_payment_details
    ADD CONSTRAINT merchant_payment_details_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES mor.merchant(id);


--
-- Name: payment_hold payment_hold_payment_id_fkey; Type: FK CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.payment_hold
    ADD CONSTRAINT payment_hold_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES mor.payment(id);


--
-- Name: payout payout_ledger_transaction_id_fkey; Type: FK CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.payout
    ADD CONSTRAINT payout_ledger_transaction_id_fkey FOREIGN KEY (ledger_transaction_id) REFERENCES mor.ledger_transaction(id);


--
-- Name: payout payout_merchant_id_fkey; Type: FK CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.payout
    ADD CONSTRAINT payout_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES mor.merchant(id);


--
-- Name: refund refund_ledger_transaction_id_fkey; Type: FK CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.refund
    ADD CONSTRAINT refund_ledger_transaction_id_fkey FOREIGN KEY (ledger_transaction_id) REFERENCES mor.ledger_transaction(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: refund refund_payment_id_fkey; Type: FK CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.refund
    ADD CONSTRAINT refund_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES mor.payment(id);


--
-- Name: tax_remittance tax_remittance_ledger_transaction_id_fkey; Type: FK CONSTRAINT; Schema: mor; Owner: -
--

ALTER TABLE ONLY mor.tax_remittance
    ADD CONSTRAINT tax_remittance_ledger_transaction_id_fkey FOREIGN KEY (ledger_transaction_id) REFERENCES mor.ledger_transaction(id);


--
-- PostgreSQL database dump complete
--

\unrestrict Bql0HVZpzafUEA9AsdsOqn0ZjVvrFzub1f48qQS6tvRCL30cMC7UGDc2oSfLDGa
