#!/usr/bin/env bash
# Dumps the current schema of the running dev database into db/schema.sql.
#
# That file is the single generated picture of the schema: pg_dump output,
# complete with constraints, indexes and defaults. Never edit it by hand -
# change a migration, apply it, and re-run this.
#
# Migrations are applied by the application at startup, or by
# ./scripts/db-migrate.sh when the code cannot compile yet.
set -euo pipefail

cd "$(dirname "$0")/.."

CONTAINER="${PG_CONTAINER:-ledger-postgres}"
DB_NAME="${DB_NAME:-ledger}"
DB_USER="${DB_USER:-ledger}"

docker exec "$CONTAINER" pg_isready -U "$DB_USER" -d "$DB_NAME" >/dev/null 2>&1 || {
  echo "Postgres container '$CONTAINER' is not running. Start it with: docker compose up -d"
  exit 1
}

# An empty database means migrations have not run yet.
tables=$(docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -At -c \
  "SELECT count(*) FROM information_schema.tables
    WHERE table_schema NOT IN ('pg_catalog','information_schema');")

if [ "${tables:-0}" -eq 0 ]; then
  echo "Database '$DB_NAME' has no tables - migrations have not run yet."
  echo "Run ./scripts/db-migrate.sh (or start the app), then re-run this script."
  exit 1
fi

mkdir -p db

echo "==> db/schema.sql"
{
  echo "-- GENERATED by scripts/db-schema.sh - do not edit."
  echo "-- Rebuild: ./scripts/db-schema.sh"
  echo
  docker exec "$CONTAINER" pg_dump -U "$DB_USER" -d "$DB_NAME" \
    --schema-only --no-owner --no-privileges --no-comments \
    --exclude-table=flyway_schema_history
} > db/schema.sql

wc -l db/schema.sql
